name: Publish to GitHub Packages

on:
  release:
    types: [prereleased, released]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2.3.4

      - name: Install Node.js 14
        uses: actions/setup-node@v3.4.0
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Install Java 15
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '15'
          java-package: jdk
          architecture: x64

      - name: Run tests against Firebase emulator
        run: |
          npm install -g firebase-tools
          firebase emulators:exec --only firestore,database --project integrify-emulator 'npm run test:ci'

  publish:
    name: Publish to GitHub packages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2.3.4
      
      - name: Install Node.js 14
        uses: actions/setup-node@v3.4.0
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: "@michaelprichardson"

      - run: echo "registry=https://npm.pkg.github.com/@michaelprichardson" >> .npmrc

      - name: Publish
        run: |
          npm ci
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
