name: Publish to GitHub Packages

on:
  release:
    types: [prereleased, released]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2.3.4

      - name: Install Node.js 14
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      # - name: Run linting
      #   run: npm run lint

      # - name: Run tests
      #   run: npm test

  publish:
    name: Publish to GitHub packages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2.3.4
      
      - name: Install Node.js 14
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: "@michaelprichardson"

      - run: echo "registry=https://npm.pkg.github.com/@michaelprichardson" >> .npmrc

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
